name: Denylist Request
description: Report missing blockable domain(s).
labels: ["deny"]
assignees: 
  - hagezi
body:
  - type: textarea
    id: domains
    attributes:
      label: Which domain(s) should be blocked?
      description: |
        Only pure domains, no adblock rules, no URLs, ...
    validations:
      required: true

  - type: checkboxes
    id: blocked
    attributes:
      options:
        - label: I confirm that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
          required: true
        - label: I confirm that I have checked that the domain(s) are not already blocked.
          required: true
          
  - type: textarea
    id: reason
    attributes:
      label: Why should these domain(s) be blocked?
      description: |
        Please provide precise details for each domain as to why they should be blocked, what is tracked and where they are accessed.
    validations:
      required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: Privacy
      description: By submitting this issue, you agree that the report will not contain any private information.
      options:
        - label: I confirm that the report does not contain any private information.
          required: true
