name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Tag
        run: echo "release_tag=$(date +'%Y.%j').$((`date +%s` % 86400 ))" >> $GITHUB_ENV     
      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.release_tag }}
          name: ${{ env.release_tag }}

  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: URLs
        id: purge_urls
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/${{ github.repository }}@latest"
          urls=""
          for f in `find adblock controld dnsmasq domains hosts ips pac rpz wildcard -name "*.txt" -o -name "*.pac" -o -name "*.json" -type f`; do
            urls+="${baseUrl}/${f},"
          done
          echo "urls=${urls%,*}" >> $GITHUB_OUTPUT

      - name: Purge
        uses: egad13/purge-jsdelivr-cache@v1.1.0
        with:
          url: ${{ steps.purge_urls.outputs.urls }}
    needs: release
         
  releasecleanup:
    name: ReleaseCleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 3
          release-drop-tag: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
    needs: [release, purge]
    
  workflowcleanup:
    name: WorkflowCleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0
    needs: [release, purge, releasecleanup]
